### ISSUE TITLE
Identifying all unique OSM hashtags

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/insights#8]
In order to validate the existence of hashtags in the data source, it will be easier to have all the unique OSM hashtags in a separate table. From what has @omranlm shared so far I believe we can extract this information from the changeset metadata and at present we have all OSM changesets from the beginning of time captured within Insights.

Population all existings hashtags will be a one time efforts and later to keep this up to date, processing script has to be updated to capture new hashtags within the table.

Leave it to @itskshitiz321 and @omranlm to decide on the best approach here.

We can prioritise this for the upcoming sprint

**Comment by ramyaragupathy** [comment]
Per discussion today we will have the existing unique hashtags populated from raw changesets as a separate table. We will modify the changeset processing script to keep this table up to date.

Hashtag definition: Anything that starts with a `#` symbol present in `hashtag` and `changeset_comment` metadata fields. Space, `,` and `;` are the separators for the unique hashtags in both the metadata fields.

cc @omranlm @itskshitiz321

**Comment by omranlm** [comment]
All done and implemented in the DB level. In table all_osm_hashtags in the insights DB we have a list of all osm hashtags and being updated every 2 minutes upon checking the new added changesets
